services:
  app:
    build:
      context: .
      args:
        DATABASE_URL: mongodb://mongo/typeracer-tonik
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    ports:
      - '4444:3000'
    depends_on:
      - mongo
    env_file:
      - .env
    restart: unless-stopped

  mongo:
    image: mongo:7
    volumes:
      - data:/data/db
    restart: unless-stopped

volumes:
  data:
