services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=mongodb://mongo:27017/typeracer-tonik
        - PAYLOAD_SECRET=${PAYLOAD_SECRET}
    ports:
      - '4444:3000'
    depends_on:
      mongo:
        condition: service_started
    environment:
      - DATABASE_URL=mongodb://mongo:27017/typeracer-tonik
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - NODE_ENV=production
    volumes:
      - media_data:/app/media
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    command: --storageEngine=wiredTiger
    restart: unless-stopped

volumes:
  mongo_data:
  media_data:
